version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_PROD}
      - POSTGRES_PASSWORD=${DB_PASS_PROD}
      - Postgres_DB=${DB_PROD}
    ports:
      - "8082:5432"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
      - Postgres_DB=${DB_TEST}
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
